
import { secureDb } from './services/db.js';
import { supabaseAdmin } from './common.js'; // Need this to clean up or force things if needed

const log = (msg) => console.log(`[VERIFY] ${msg}`);

async function run() {
    log('Starting Refund Logic Verification...');
    const context = {
        performed_by: '00000000-0000-0000-0000-000000000000',
        user: { id: '00000000-0000-0000-0000-000000000000', email: 'system@test.com' },
        userProfile: { role: 'admin', name: 'System Admin' },
        reason: 'Verification Script'
    };

    try {
        // 1. Get or Create a User (Admin)
        let admin = await secureDb.get('users', q => q.eq('email', 'admin_test_refund@example.com').single());
        if (!admin) {
            log('Creating Admin User...');
            try {
                // If using auth.users is hard, we just insert into public.users if it's the main table.
                // But typically users is linked to auth.users. 
                // For simplified verification we use secureDb.create on 'users' which is public.users usually.
                admin = await secureDb.create('users', {
                    email: 'admin_test_refund@example.com',
                    name: 'Admin For Refund',
                    role: 'admin',
                    // Create a dummy ID if not auto-generated by trigger on public.users 
                    // Usually public.users entries are created via trigger from auth.users.
                    // If we can't create straight into users, this might fail.
                }, context);
            } catch (e) {
                log('Could not create admin user (might need auth user trigger). Using any existing user.');
                // Fallback: pick any user
                const users = await secureDb.get('users', q => q.limit(1));
                if (users.length > 0) admin = users[0];
            }
        }

        if (!admin) throw new Error("No user found/created to act as Approver");
        log(`Using Admin: ${admin.id} (${admin.name})`);

        // 2. Create Student
        let student = await secureDb.get('users', q => q.eq('role', 'student').limit(1).single());
        // If not found, create one
        if (!student) {
            student = await secureDb.create('users', { email: 'student_ref@test.com', name: 'Student Ref', role: 'student' }, context);
        }
        log(`Using Student: ${student.id}`);

        // 3. Create Fee & Transaction (Minimal) to satisfy FK
        // Need assignment -> transaction
        // But checking `refund_requests` schema: transaction_id IS FK.
        // We need a transaction.

        // Fee Cat
        const cat = await secureDb.create('fee_categories', { name: 'Ref Cat' }, context);
        // Fee Struct
        const struct = await secureDb.create('fee_structures', { name: 'Ref Struct', batch_year: 2025, due_date: '2025-01-01', category_id: cat.id }, context);
        // Assignment
        const assign = await secureDb.create('student_fee_assignments', {
            student_id: student.id, structure_id: struct.id, total_amount: 1000, net_amount: 1000
        }, context);
        // Transaction
        const tx = await secureDb.create('transactions', {
            student_id: student.id, assignment_id: assign.id, amount: 500, payment_method: 'cash'
        }, context);

        log(`Created Transaction: ${tx.id}`);

        // 4. Create Refund Request
        const refund = await secureDb.create('refund_requests', {
            transaction_id: tx.id,
            student_id: student.id,
            amount: 100,
            reason: 'Test Refund',
            status: 'requested',
            requested_by: student.id
        }, context);

        log(`Created Refund Request: ${refund.id} (Status: ${refund.status})`);

        // 5. ATTEMPT APPROVE (The core logic test)
        log('Attempting Approval via secureDb.update...');

        const updatePayload = {
            status: 'approved',
            approved_by: admin.id,
            processed_date: new Date()
        };

        const updated = await secureDb.update('refund_requests', refund.id, updatePayload, context);

        log(`Update Result: Status=${updated.status}, ApprovedBy=${updated.approved_by}`);

        if (updated.status === 'approved' && updated.approved_by === admin.id) {
            log('✅ SUCCESS: Refund Approved Logic works.');
        } else {
            log('❌ FAILURE: Update returned but fields not match?');
            console.log(updated);
        }

    } catch (e) {
        log(`❌ CRITICAL ERROR: ${e.message}`);
        console.error(e);
    }

    process.exit(0);
}

run();
